- hosts: master
  become: true
  roles:
    - prova
    - wildfly
    - master
    - oracle-java
    - driver
- hosts: slave
  become: true
  roles:
    - prova
    - wildfly
    - slave
    - driver
