- name: Disable Selinux
  selinux:
    policy: targeted
    state: permissive
- selinux:
    state: disabled
- name: stop and Disable firewalld
  firewalld:
     state: disabled
     profiles:
    - Domain
  tags: disable_firewall
