- name: Configurazione host.xml
  template:
    src: host.file
    dest: /opt/wildfly-11.0.0.Final/domain/configuration/host.xml
    owner: wildfly
    group: wildfly
- replace:
    path: /opt/wildfly-11.0.0.Final/domain/configuration/host.xml
    regexp: "192.168.140.131"
    replace: "{{hostvars[item]['ansible_default_ipv4']['address']}}"
  with_items:
    - "{{ groups['master'] }}"
