- name: init.d
  template:
    src: init.d
    dest: /opt/wildfly-11.0.0.Final/bin/init.d/wildfly-init-redhat.sh
    owner: wildfly
    group: wildfly
- name: reload daemon systemctl
  systemd: daemon_reload=yes
